sudo: false
dist: trusty
language: python
python:
- '2.7'
- '3.6'
install:
- pip install -r requirements.txt
- pip install --force-reinstall pylint==1.9.2
script:
- pylint Adafruit_PureIO/smbus.py
deploy:
  provider: pypi
  user: adafruit-travis
  password:
    secure: WF+gNAM1RJd73JwH2oaoOz8fpAlfEhT7O6fV9fzX7qyryRCRgXPQdTvsNZgcjJ+rjkAZvIB4pLKDI2ZRxUIs0wonvDTfqRRs0N0aKxshVZZo15+Xdy2NkS5/HhBGMZpVeRWj5k2a70vxmyrbwnzlEaqeT4eiDFVpUYJsAnJkijWfWJSxL1Rl3nuG4D/HF+QTUoxHZBVoqQec4eAuy0/k7dpE0feaRiIdAYokyd2PVe8k6Ii4zmcUwDGPwsky064CLtuRaG5asMeeFQ3tlLi8jaTEcVkkYMTcXwMhX+9fkwaxgtfWH3qFnAnUxODWuuLpp5ZfTaKLKnMx74+RSgJVGD1byblcaY3LVBjqXKrY/arWUsHreoE8a/BLp5sAisUlnLXkF8u+NzrL/NqJhoJUwTLb6H5JOHtjvk/qnvuNgD77bqqJfv7EyhW9kf1TUpTJPtsNpTA4N0DOlQ/nnp0O111QLjJvRi/S/98d/Na8W2o6KX/2ytKmU5v1RnWpcnjP6xqDYzpoYOj7VjFyG/LTk+TACDOqm5uLRDvhFsVrjluS6d9CcjFPtXWEgMMCdIkLF4quPqe+QB7IWnfMrCbSJZJh2ZYowKQVyZqZ/5eCSetTuI93PD8ZVUmWDFnYE/oCCPA+GhJno6Zmxs1dtGjFFwAV7H6jPjaNmZTRWvX514k=
  on:
    tags: true
    python: '3.6'
